import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import { auth } from "@/app/lib/auth";
import {Theme, ThemeProvider} from "@/app/components/ThemeProvider";
import {cookies} from "next/headers";
import Script from "next/script";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
    title: "FinanTrack",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const user = await auth();
    const cookieStore = await cookies()
    const theme: Theme = cookieStore.get('theme')?.value === 'light' ? "light" : "dark";
    return (
        <html lang="en" className={theme === "dark" ? "dark" : ""} style={{colorScheme: theme}}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <ThemeProvider initialTheme={theme}>
            <Navbar initialAuth={!!user} />
            <main>{children}</main>
            <Footer />
        </ThemeProvider>

        <Script
            src="https://www.googletagmanager.com/gtag/js?id=G-3NXS99FQF6"
            strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
            {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-3NXS99FQF6');
          `}
        </Script>
        </body>
        </html>
    );
}
